set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33}  [get_ports clk]
create_clock -period 10.00 [get_ports clk]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports reset]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports enable]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {ssdAnode[0]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {ssdAnode[1]}] 
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {ssdAnode[2]}] 
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {ssdAnode[3]}] 
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {ssdAnode[4]}] 
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {ssdAnode[5]}] 
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {ssdAnode[6]}] 
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {ssdAnode[7]}]  
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {ssdCathode[0]}] 
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {ssdCathode[1]}] 
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {ssdCathode[2]}] 
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports {ssdCathode[3]}] 
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {ssdCathode[4]}] 
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports {ssdCathode[5]}] 
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {ssdCathode[6]}] 

